name = "orbic-storage"
main = "src/index.ts"
compatibility_date = "2024-10-25"
compatibility_flags = ["nodejs_compat"]
routes = [{ pattern = "storage.orbic.me", custom_domain = true }]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "orbic-bucket"

[[kv_namespaces]]
binding = "KV"
id = "83bb578f92ff493c9f7f751ff39e0d0f"

[build]
command = "bun run build:ts"

[observability.logs]
enabled = true
